# K-NN (K NEAREST NEIGHBOUR)


In [1]:
import numpy as  np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data "
#assign coloumn names to the dataset
names=['sepal-length','sepal-width','petal-length','petal width','class']
#asssign datset to pandas 
dataset=pd.read_csv(url,names=names)

In [4]:
dataset.head()

sepal-length  sepal-width  petal-length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
#split datset into its attributes and labels
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:, 4].values

In [7]:
#training and testing splits
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [20]:
#import model
from sklearn.neighbors import KNeighborsClassifier
Classifier=KNeighborsClassifier(n_neighbors=5)
Classifier.fit(x_train,y_train)



ImportError: cannot import name 'KNeighborsclassifier' from 'sklearn.neighbors' (E:\anaconda\lib\site-packages\sklearn\neighbors\__init__.py)

In [23]:
y_pred=Classifier.predict(x_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.93      0.93      0.93        14
 Iris-virginica       0.80      0.80      0.80         5

       accuracy                           0.93        30
      macro avg       0.91      0.91      0.91        30
   weighted avg       0.93      0.93      0.93        30

[[11  0  0]
 [ 0 13  1]
 [ 0  1  4]]
